const CONFIG = {
  OPENROUTER_API_KEY: 'ISI_API_KEY_IYH_KAMU_DISINI',
  OPENROUTER_MODEL:   'gemini-3-flash',

  SUPABASE_URL:      'https://YOUR_PROJECT_ID.supabase.co',
  SUPABASE_ANON_KEY: 'YOUR_SUPABASE_ANON_KEY',
  SUPABASE_TABLE:    'nama_tabel_kamu',

  DATA_SOURCE: 'supabase',

  COLUMN_MAP: {
    order_id:        'SalesOrderID',
    order_date:      'OrderDate',
    ship_date:       'ShipDate',
    ship_method:     'ShipMethod',
    customer_id:     'CustomerID',
    customer_name:   'CustomerName',
    segment:         'Segment',
    country_region:  'CountryRegion',
    city:            'City',
    province:        'Province',
    postal_code:     'PostalCode',
    region:          'Territory',
    product_name:    'ProductName',
    category:        'Category',
    sub_category:    'SubCategory',
    qty:             'Qty',
    unit_price:      'UnitPrice',
    sales:           'Sales',
    discount:        'Discount',
    product_cost:    'ProductCost',
    total_cost:      'TotalCost',
    profit:          'Profit',
  },
};
